### PR TITLE
Missing array sizes for hashes serialization

### PR DESCRIPTION
**Pull request by baloo**
see https://github.com/RustCrypto/hashes/pull/574 for more context

### CODE REVIEW

**Comment by tarcieri** [comment]
Hmm, I think it'd be good to keep the sizes which aren't gated under `extra_sizes` consistent according to the rules documented at the top of the module.

Maybe we can just expand the sizes that are always available up to 512.

**Comment by tarcieri** [comment]
I opened #65 as an alternative which supports all array sizes up to 512

**Comment by tarcieri** [comment]
Closing in favor of #67

**Comment by baloo** [comment]
I didn't read the rules on top of the module. My bad.

**Pull request closed without merging**
